FROM icecube/icetray:combo-stable

ARG TORCH=1.9.1
ARG PYG=2.0.1
ARG CUDA=cpu

RUN pip install torch==${TORCH}+${CUDA} -f https://download.pytorch.org/whl/${CUDA}/torch_stable.html && \
    pip install torch-cluster torch-scatter torch-sparse torch-spline-conv torch-geometric==${PYG} -f https://data.pyg.org/whl/torch-${TORCH}+${CUDA}.html

RUN pip install git+https://github.com/icecube/graphnet.git#egg=graphnet[develop]

WORKDIR /root

CMD [ "/bin/bash" ]