FROM icecube/icetray:combo-stable

ARG TORCH=1.9.1
ARG PYG=2.0.1
ARG CUDA=cpu

RUN pip install --upgrade pip && \
    pip install wheel setuptools==59.5.0 && \
    pip install --upgrade astropy && \
    pip install --ignore-installed PyYAML && \
    pip install torch==${TORCH}+${CUDA} -f https://download.pytorch.org/whl/${CUDA}/torch_stable.html && \
    pip install torch-cluster==1.5.9 -f https://data.pyg.org/whl/torch-${TORCH}+${CUDA}.html && \
    pip install torch-scatter==2.0.9 -f https://data.pyg.org/whl/torch-${TORCH}+${CUDA}.html && \
    pip install torch-sparse==0.6.12 -f https://data.pyg.org/whl/torch-${TORCH}+${CUDA}.html && \
    pip install torch-spline-conv==1.2.1 -f https://data.pyg.org/whl/torch-${TORCH}+${CUDA}.html && \
    pip install torch-geometric==${PYG} -f https://data.pyg.org/whl/torch-${TORCH}+${CUDA}.html

RUN pip install git+https://github.com/icecube/graphnet.git#egg=graphnet[develop,torch]

WORKDIR /root

CMD [ "/bin/bash" ]