name: 'Install graphnet'
description: 'Installs graphnet package'

inputs:
  editable:
    description: "Whether to install graphnet as editable"
    required: true
    default: false
  user:
    description: "Whether to install graphnet as user"
    required: true
    default: false
  extras:
    description: "Extras flags for pip installation of graphnet"
    required: true
    default: "develop"

  torch_version:
    description: "Version of PyTorch"
    required: true
    default: "2.6.0"
    options: ["2.7.0", "2.6.0", "2.5.0", "2.4.0"]

  hardware:
    description: "The requirements file depends on the hardware, i.e., CPU, GPU, or macOS"
    required: true
    default: "cpu"
    options: ["cpu", "cu118", "cu121", "cu124", "cu126", "macos"]

  use_vm:
    description: "Should the installation happen in a virtual environment named venv?"
    required: true
    default: false
    options: [true, false]

runs:
  using: "composite"
  steps:
    - name: Prepare pip flags
      id: flags
      run: |
        [[ "${{ inputs.editable }}" == "true" ]] && echo "editable_flag=-e" >> $GITHUB_OUTPUT || echo "editable_flag=" >> $GITHUB_OUTPUT
        [[ "${{ inputs.user }}" == "true" ]] && echo "user_flag=--user" >> $GITHUB_OUTPUT || echo "user_flag=" >> $GITHUB_OUTPUT

        version="${{ inputs.torch_version }}"
        IFS='.' read -r major minor _ <<< "$version"
        echo "torch_flag=${major}${minor}" >> $GITHUB_OUTPUT
      shell: bash

    - name: Install dependencies (pip & setuptools)
      shell: bash
      run: |
        if [[ "${{ inputs.use_vm }}" == "true" ]]; then source ~/venv/bin/activate; fi
        pip install --upgrade 'pip>=20'
        pip install --upgrade 'setuptools>=68.2.2'

    - name: Print pip and setuptools versions
      shell: bash
      run: |
        if [[ "${{ inputs.use_vm }}" == "true" ]]; then source ~/venv/bin/activate; fi
        pip --version
        pip show setuptools

    - name: Install GraphNeT
      shell: bash
      run: |
        if [[ "${{ inputs.use_vm }}" == "true" ]]; then source ~/venv/bin/activate; fi

        echo "Installing graphnet with flags: ${{ steps.flags.outputs.user_flag }} ${{ steps.flags.outputs.editable_flag }}"
        pip install ${{ steps.flags.outputs.user_flag }} ${{ steps.flags.outputs.editable_flag }} .[torch-${{ steps.flags.outputs.torch_flag }}-${{ inputs.hardware }},${{ inputs.extras }}] \
          -f https://data.pyg.org/whl/torch-${{ inputs.torch_version }}+${{ inputs.hardware }}.html

        pip install git+https://github.com/thoglu/jammy_flows.git
