name: 'Install graphnet'
description: 'Installs graphnet package'

inputs:
  editable:
    description: "Whether to install graphnet as editable"
    required: true
    default: false
  user:
    description: "Whether to install graphnet as user"
    required: true
    default: false
  extras:
    description: "Extras flags for pip installation of graphnet"
    required: true
    default: "[develop,torch]"
  hardware:
    description: "The requirements file depends on the hardware, i.e., CPU, GPU, or macOS"
    required: true
    default: "cpu"
    options: ["cpu", "gpu", "macos"]

runs:
  using: "composite"
  steps:
    - name: Infer installation flags
      run: |
        PIP_FLAG_EDITABLE=`[[ ${{ inputs.editable }} =~ (T|t)rue ]] && printf "%s\n" "-e " || echo " "`
        PIP_FLAG_USER=`[[ ${{ inputs.user }} =~ (T|t)rue ]] && printf "%s\n" "--user " || echo " "`
        echo "PIP_FLAGS=${PIP_FLAG_USER}${PIP_FLAG_EDITABLE}" >> $GITHUB_ENV
      shell: bash
    - name: Install dependencies
      run: |
        pip install --upgrade pip>=20
        pip install wheel setuptools==59.5.0
      shell: bash
    - name: Install package
      run: |
        pip install -r requirements/torch_${{ inputs.hardware }}.txt ${{ env.PIP_FLAGS }} .${{ inputs.extras }}
      shell: bash
