name: Create Docker Images

on:
  # 1) Manual trigger from the Actions tab
  workflow_dispatch:

  # 2) When a GitHub Release is published
  release:
    types: [published]

  # 3) When pull requests are merged into the default branch (e.g. main)
  pull_request:
    types: [closed]
    branches:
      - main     # change if your default branch is different
      # - stable  # add more target branches if needed

jobs:
  build:
    # run if:
    # - not a PR event (i.e., release or manual), OR
    # - it *is* a PR event and the PR was merged
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    name: Docker Image - ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: graphnet-latest-torch26-cpu-icetray-devel-v1.13.0-ubuntu22.04-2025-02-12
            TORCH_CHOICE: torch-2.6.0
            HARDWARE: cpu
            DOCKERFILE_PATH: docker/icetray/Dockerfile
            BASE_IMAGE: "icecube/icetray:icetray-devel-v1.13.0-ubuntu22.04-2025-02-12"
            DOCKERHUB_NAME: rorsoe/graphnet_icetray
          - name: graphnet-latest-torch26-cpu-ubuntu22.04
            TORCH_CHOICE: torch-2.6.0
            HARDWARE: cpu
            DOCKERFILE_PATH: docker/standalone/Dockerfile
            BASE_IMAGE: ubuntu:22.04
            DOCKERHUB_NAME: rorsoe/graphnet
          - name: graphnet-latest-torch26-cu126-ubuntu22.04
            TORCH_CHOICE: torch-2.6.0
            HARDWARE: cu126
            DOCKERFILE_PATH: docker/standalone/Dockerfile
            BASE_IMAGE: ubuntu:22.04
            DOCKERHUB_NAME: rorsoe/graphnet
    uses: graphnet-team/graphnet/.github/actions/docker_action.yml@main #./.github/actions/docker/docker_action.yml
    with:
      DOCKERHUB_NAME: ${{ matrix.DOCKERHUB_NAME }}
      GRAPHNET_VERSION: main
      BASE_IMAGE: ${{ matrix.BASE_IMAGE }}
      HARDWARE: ${{ matrix.HARDWARE }}
      TORCH_CHOICE: ${{ matrix.TORCH_CHOICE}}
      PYTHON_VERSION: "3.11"
      PLATFORMS: linux/amd64
      CONTEXT_PATH: "."
      DOCKERFILE_PATH: ${{ matrix.DOCKERFILE_PATH }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN:    ${{ secrets.DOCKERHUB_TOKEN }}
